/*
 * example.c — a C caller for the Rust functions exported in this module.
 *
 * This file is NOT compiled by `cargo test`. It's provided as a reference
 * for what the real C caller would look like.
 *
 * To compile and run (after building the Rust crate as a cdylib):
 *
 *   1. Add `crate-type = ["cdylib"]` to the [lib] section of Cargo.toml.
 *   2. Build: cargo build --release
 *   3. Compile C: gcc example.c -L target/release -lmodule_053_solutions -o example
 *   4. Run: LD_LIBRARY_PATH=target/release ./example
 */

#include <stdio.h>
#include <stdint.h>
#include <stddef.h>

/* These would normally come from a header generated by cbindgen. */
int32_t rust_add(int32_t a, int32_t b);
double rust_multiply(double a, double b);
size_t rust_strlen(const char *s);

typedef struct {
    double width;
    double height;
} Rectangle;

double rust_rectangle_area(const Rectangle *r);
int32_t rust_sum_array(const int32_t *data, size_t len);

int main(void) {
    printf("rust_add(3, 4) = %d\n", rust_add(3, 4));
    printf("rust_multiply(3.0, 4.0) = %.2f\n", rust_multiply(3.0, 4.0));
    printf("rust_strlen(\"hello\") = %zu\n", rust_strlen("hello"));

    Rectangle r = {5.0, 3.0};
    printf("rust_rectangle_area({5.0, 3.0}) = %.2f\n", rust_rectangle_area(&r));

    int32_t data[] = {1, 2, 3, 4, 5};
    printf("rust_sum_array([1,2,3,4,5]) = %d\n", rust_sum_array(data, 5));

    return 0;
}
